spring:
  application:
    name: login-module
  datasource:
    username: remote_user
    password: Iliyaj@090
    url: jdbc:mysql://13.53.83.119:3306/exam_portal
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
